server:
  port: 80

jwt:
  header: Authorization
  secret: datastudio
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

jdatastudio:
  cloud: false
  tenant:
    uri: mongodb://localhost:27017/testLocal2
    admin: gongxinong@gmail.com
  storage:
    strategy: jds
    rootPath: /Users/gongmark/data/jds
    endpoint: http://oss-cn-shanghai.aliyuncs.com

spring:
  application:
    name: jdatastudio-admin
  data:
    mongodb:
      uri: mongodb://192.168.202.238:27017/jdatastudio